### ISSUE TITLE
Inconsistent license

### ISSUE THREAD

**Issue by VehpuS** [chetanraj/awesome-github-badges#4]
The license in the LICENSE file is CC0 while the license in your readme is Creative Commons Attribution-ShareAlike 4.0 International license. Those are VERY different licenses (SA is more restrictive - as it is a copyleft license). You should probably display one consistently in both places (or just remove the readme notice if it is a mistake).

**Comment by chetanraj** [comment]
thanks @VehpuS  , modified the README file
